name: Documentation

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: macos-latest
    steps:
      - name: Switch to Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_13.app/Contents/Developer
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Run Jazzy
        uses: sersoft-gmbh/swifty-docs-action@v1
        with:
          xcodebuild-destination: 'platform=iOS Simulator,OS=latest,name=iPhone 11'
          output: docs
      - name: Update gh-pages branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}